spring:
  application:
    name: products-service

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
