spring:
  application:
    name: shopcart-service

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/posts_service?serverTimezone=UTC

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka